### PR TITLE
Adding my open source contribution

### PR DESCRIPTION
**Pull request by aabrahamian**
thanks for the consideration

### CODE REVIEW

**Comment by lookersandbox** [comment]
Just checking that @clabot can't actually do anything about this yet (haven't given permissions)

**Comment by lookersandbox** [comment]
Ok just gave clabot permissions
@clabot check

**Comment by lookersandbox** [comment]
Maybe I had to wait a second, trying again
@clabot check

**Comment by lookersandbox** [comment]
Fixed JSON, this should work
@clabot check

**Comment by lookersandbox** [comment]
Looks like clabot needs to be setup before the PR is made, try closing and reopening your PR

**Comment by aabrahamian** [comment]
Ok will do

**Pull request closed without merging**
